# Generated by Django 2.2 on 2019-08-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='tecnologia',
        ),
        migrations.AddField(
            model_name='sessao',
            name='tecnologia',
            field=models.IntegerField(choices=[(1, '2D'), (2, '3D')], default=1),
        ),
    ]
